env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jquery: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  array-bracket-spacing:
    - error
    - never
  object-curly-spacing:
    - error
    - never
  computed-property-spacing:
    - error
    - never
  space-before-blocks:
    - error
    - always
