variables:
  VERSION_ID: '0.1.$CI_PIPELINE_ID'

stages:
  - build
  
build:
  image: electronjs/build
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.*
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - npm install
    - rm -rf node_modules/gulp-autoprefixer
    - npm install gulp-autoprefixer@2.3.1
    - npm build