.buildTemplate:
  variables:
    CI_DEBUG_TRACE: "false"
  image: electronuserland/builder:wine
  artifacts:
    expire_in: 3 days
    paths:
      - $CI_PROJECT_DIR/dist/*.*
  before_script:
    - npm install
    
# Build for all commits, shorter expiry
# Builds Win and Mac tar.gz only, due to unavailability of Mac image
# Used by App during testing period, till v1.0 release
build:
  extends: .buildTemplate
  script:
    - npm i -g eslint && eslint init && npm run lint
    - npm run buildWin && npm cache --force clean && npm run buildMac
    - echo 'Built for Windows and Mac tar.gz; commit ' $CI_COMMIT_MESSAGE
  except:
    - tags

# Build for Tags only, expiry extended
# Builds all platforms
# Should change feedURL for AutoUpdater to this Job after v1.0 release
releaseBuild:
  extends: .buildTemplate
  only:
    - tags
  artifacts:
    expire_in: 3 years
  script:
    - npm i -g eslint && eslint init && npm run lint
    - npm run build
    - echo 'Built for all platforms; tag ' $CI_COMMIT_TAG