.buildTemplate:
  variables:
    CI_DEBUG_TRACE: "false"
  image: electronuserland/builder:wine
  artifacts:
    expire_in: 30 days
    paths:
      - $CI_PROJECT_DIR/dist/*.*
  before_script:
    - npm install
    
# Build for all commits, shorter expiry
# Used by App during testing period, till v1.0 release
build:
  extends: .buildTemplate
  script:
    - npm run buildWin && npm cache --force clean && npm run buildMac
    - echo 'Built for commit ' $CI_COMMIT_MESSAGE

# Build for Tags only, expiry extended
# Should change feedURL for AutoUpdater to this Job after v1.0 release
releaseBuild:
  extends: .buildTemplate
  only:
    - tags
  artifacts:
    expire_in: 3 years
  script:
    - npm run buildWin && npm cache --force clean && npm run buildMac
    - echo 'Built for Windows and Mac; tag ' $CI_COMMIT_TAG